
---
settings:
  concurrency: 4

# The following env vars need to be set for DO:
#
# - DIGITALOCEAN_CLIENT_ID
# - DIGITALOCEAN_API_KEY
# - SSH_KEY_IDS
#
driver:
  name: digitalocean

provisioner:
  name: shell
  data_path: .

platforms:
  - name: ubuntu-1004
    driver_config:
      image_id: 14097
      flavor_id: 63
      region_id: 4

  - name: ubuntu-1204
    driver_config:
      image_id: 3101045
      flavor_id: 63
      region_id: 4

  - name: ubuntu-1310
    driver_config:
      image_id: 3101918
      flavor_id: 63
      region_id: 4

  - name: debian-60
    driver_config:
      image_id: 12573
      flavor_id: 63
      region_id: 4

  - name: debian-70
    driver_config:
      image_id: 3445812
      flavor_id: 63
      region_id: 4

  - name: centos-64
    driver_config:
      image_id: 562354
      flavor_id: 63
      region_id: 4

  - name: centos-65
    driver_config:
      image_id: 3448641
      flavor_id: 63
      region_id: 4

  - name: centos-58
    driver_config:
      image_id: 1601
      flavor_id: 63
      region_id: 4

  - name: fedora-19
    driver_config:
      image_id: 3102879
      flavor_id: 62
      region_id: 4

  - name: fedora-20
    driver_config:
      image_id: 3243145
      flavor_id: 63
      region_id: 4

  - name: arch-201305
    driver_config:
      image_id: 350424
      flavor_id: 63
      region_id: 4

suites:
  - name: default
