language: ruby
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.1
bundler_args: --without development_extras
script:
- bundle exec rake prep --trace
- bundle exec rake compile --trace
- bundle exec rake headers --trace
- bundle exec rake travis --trace
