language: ruby
branches:
  only:
    - master
before_install:
  - sudo dpkg -P libyajl1 || true
  - gem install bundler
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem update --system
  - gem --version
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - ruby-head
  - rbx-2.2
  - jruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  allow_failures:
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: openjdk7
    - rvm: rbx-2.2
      jdk: oraclejdk7
  exclude:
    - rvm: 2.1.10
      jdk: openjdk6
    - rvm: 2.1.10
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: rbx-2.2
      jdk: openjdk6
    - rvm: rbx-2.2
      jdk: openjdk7
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: jruby-head
      jdk: openjdk6
bundler_args: --without development_extras --jobs 3 --retry 3
script:
  - bundle exec rake prep --trace
  - bundle exec rake compile --trace
  - bundle exec rake headers --trace
  - bundle exec rake travis --trace
